pipeline{
    agent{
        label "cirhos_rhel7"
    }

    environment {
        OCM_ACCESS_TOKEN = credentials('ocm-token-id')
    }

    options {
        ansiColor('gnome-terminal')
        timeout(time: 2, unit: 'HOURS')
        timestamps()
    }

    stages{
        stage("Clone integreatly-operator repository"){
            steps{
                git(
                    url: 'git@github.com/psturc/integreatly-operator.git',
                    branch: 'INTLY-4808'
                )
            }
            post{
                always{
                    echo "========always========"
                }
                success{
                    echo "========A executed successfully========"
                }
                failure{
                    echo "========A execution failed========"
                }
            }
        }
        stage("Login to ocm"){
            steps{
                sh "make OCM_TOKEN=${OCM_ACCESS_TOKEN} ocm/login"
                
            }
            post{
                always{
                    echo "========always========"
                }
                success{
                    echo "========A executed successfully========"
                }
                failure{
                    echo "========A execution failed========"
                }
            }
        }
        stage("Create a cluster config from the template"){
            steps{
                sh "make ocm/cluster.json"
                
            }
            post{
                always{
                    echo "========always========"
                }
                success{
                    echo "========A executed successfully========"
                }
                failure{
                    echo "========A execution failed========"
                }
            }
        }
        stage("Create an OSD cluster and wait until it's ready"){
            steps{
                sh "make ocm/cluster/create"
                
            }
            post{
                always{
                    echo "========always========"
                }
                success{
                    echo "========A executed successfully========"
                }
                failure{
                    echo "========A execution failed========"
                }
            }
        }

        stage("Get cluster credentials"){
            steps{
                sh "make ocm/cluster/get_credentials"
                
            }
            post{
                always{
                    echo "========always========"
                }
                success{
                    echo "========A executed successfully========"
                }
                failure{
                    echo "========A execution failed========"
                }
            }
        }

        stage("Copy cluster credentials to .kubeconfig"){
            steps{
                sh "cp ocm/cluster.kubeconfig ~/.kube/config"
                
            }
            post{
                always{
                    echo "========always========"
                }
                success{
                    echo "========A executed successfully========"
                }
                failure{
                    echo "========A execution failed========"
                }
            }
        }

        stage("Install RHMI"){
            steps{
                sh "make ocm/install/rhmi-addon"
                
            }
            post{
                always{
                    echo "========always========"
                }
                success{
                    echo "========A executed successfully========"
                }
                failure{
                    echo "========A execution failed========"
                }
            }
        }
        stage("Run the test suite"){
            steps{
                echo "TBD"
                
            }
            post{
                always{
                    echo "========always========"
                }
                success{
                    echo "========A executed successfully========"
                }
                failure{
                    echo "========A execution failed========"
                }
            }
        }
    }
    post {
        failure {
            mail(
                to: 'psturc@redhat.com',
                subject: 'OSD 4 RHMI installation pipeline failed',
                body: "See the pipeline here: ${env.RUN_DISPLAY_URL}"
            )
        }
    }
}